// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metrics

import (
	metricscommon "github.com/pingcap/tidb/pkg/metrics/common"
	"github.com/prometheus/client_golang/prometheus"
)

// EXPLAIN FORMAT='RU' demo metrics.
var (
	ExplainRUObservedTiDBRUCounter    *prometheus.CounterVec
	ExplainRUWorkRowsCounter          *prometheus.CounterVec
	ExplainRUWorkBytesCounter         *prometheus.CounterVec
	ExplainRURowWidthHistogram        *prometheus.HistogramVec
	ExplainRUStatementsCounter        *prometheus.CounterVec
	ExplainRURenderDurationHistogram  *prometheus.HistogramVec
	ExplainRUComponentSnapshotCounter *prometheus.CounterVec
)

// InitExplainRUMetrics initializes metrics for EXPLAIN ANALYZE FORMAT='RU'.
func InitExplainRUMetrics() {
	ExplainRUObservedTiDBRUCounter = metricscommon.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "observed_tidb_ru_total",
			Help:      "Counter of TiDB-side RU values generated by EXPLAIN ANALYZE FORMAT='RU'.",
		}, []string{"section", "component", "operator", "source"},
	)
	ExplainRUWorkRowsCounter = metricscommon.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "work_rows_total",
			Help:      "Counter of row-count model inputs generated by EXPLAIN ANALYZE FORMAT='RU'.",
		}, []string{"section", "component", "operator", "source"},
	)
	ExplainRUWorkBytesCounter = metricscommon.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "work_bytes_total",
			Help:      "Counter of byte-shaped model inputs generated by EXPLAIN ANALYZE FORMAT='RU'.",
		}, []string{"section", "component", "operator", "source"},
	)
	ExplainRUStatementsCounter = metricscommon.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "statements_total",
			Help:      "Counter of EXPLAIN ANALYZE FORMAT='RU' statement status.",
		}, []string{LblType},
	)
	ExplainRURenderDurationHistogram = metricscommon.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "render_duration_seconds",
			Help:      "Histogram of EXPLAIN ANALYZE FORMAT='RU' render duration.",
			Buckets:   prometheus.DefBuckets,
		}, []string{LblType},
	)
	ExplainRURowWidthHistogram = metricscommon.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "row_width",
			Help:      "Histogram of row-width factors generated by EXPLAIN ANALYZE FORMAT='RU'.",
			Buckets:   prometheus.ExponentialBuckets(1, 2, 12),
		}, []string{"component", "operator", "source"},
	)
	ExplainRUComponentSnapshotCounter = metricscommon.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: "tidb",
			Subsystem: "explain_ru",
			Name:      "component_snapshot_total",
			Help:      "Counter of EXPLAIN ANALYZE FORMAT='RU' component snapshot status.",
		}, []string{LblType},
	)
}

// RecordExplainRUStatus records a bounded FORMAT='RU' statement status.
func RecordExplainRUStatus(status string) {
	if ExplainRUStatementsCounter == nil || status == "" {
		return
	}
	ExplainRUStatementsCounter.WithLabelValues(status).Inc()
}

// ObserveExplainRURenderDuration records a bounded FORMAT='RU' render duration.
func ObserveExplainRURenderDuration(status string, seconds float64) {
	if ExplainRURenderDurationHistogram == nil || status == "" || seconds < 0 {
		return
	}
	ExplainRURenderDurationHistogram.WithLabelValues(status).Observe(seconds)
}

// RecordExplainRUComponentSnapshot records component snapshot availability.
func RecordExplainRUComponentSnapshot(status string) {
	if ExplainRUComponentSnapshotCounter == nil || status == "" {
		return
	}
	ExplainRUComponentSnapshotCounter.WithLabelValues(status).Inc()
}

// ObserveExplainRURow records bounded numeric samples from generated FORMAT='RU' rows.
func ObserveExplainRURow(section, component, operator, source, rowWidthSource string, tidbRU, workRows, workBytes, rowWidth float64) {
	if ExplainRUObservedTiDBRUCounter != nil && tidbRU >= 0 {
		ExplainRUObservedTiDBRUCounter.WithLabelValues(section, component, operator, source).Add(tidbRU)
	}
	if ExplainRUWorkRowsCounter != nil && workRows >= 0 {
		ExplainRUWorkRowsCounter.WithLabelValues(section, component, operator, source).Add(workRows)
	}
	if ExplainRUWorkBytesCounter != nil && workBytes >= 0 {
		ExplainRUWorkBytesCounter.WithLabelValues(section, component, operator, source).Add(workBytes)
	}
	if ExplainRURowWidthHistogram != nil && rowWidth > 0 && operator != "" {
		ExplainRURowWidthHistogram.WithLabelValues(component, operator, rowWidthSource).Observe(rowWidth)
	}
}
